name: Publish Docker images
on:
  push:
    branches:
      - master
jobs:
  push_nginx_arm_registry:
    name: Nginx to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image php nginx
        run:  cd nginx/1.9/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-nginx
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-nginx
  push_es_registry:
    name: Elasticsearch to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image elasticsearch 7.16.3
        run:  cd elasticsearch/7.16.3/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-elasticsearch:7.16.3
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-elasticsearch:7.16.3
  push_redis_registry:
    name: Redis to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image redis 6.2
        run:  cd redis/6.2/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-redis:6.2
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-redis:6.2
  push_varnish_registry:
    name: Varnish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image varnish 6.5
        run:  cd varnish/6.5/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-varnish:6.5
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-varnish:6.5
      - name: Build image varnish 7.0
        run:  cd varnish/7.0/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-varnish:7.0
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-varnish:7.0
  push_to_registry:
    name: PHP to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image php 8.1-cli
        run:  cd php/8.1-cli/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-php:8.1-cli
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-php:8.1-cli
      - name: Build image php 8.1-fpm
        run:  cd php/8.1-fpm/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-php:8.1-fpm
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-php:8.1-fpm
      - name: Build image php 7.4-cli
        run:  cd php/7.4-cli/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-php:7.4-cli
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-php:7.4-cli
      - name: Build image php 7.4-fpm
        run:  cd php/7.4-fpm/; docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/magento-php:7.4-fpm
      - name: Push image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/magento-php:7.4-fpm