name: Publish Docker images
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run:  cd php/7.4-cli/; docker build . --file Dockerfile --tag sashas777/magento-php:7.4-cli
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: |
          docker tag image sashas777/magento-php:7.4-cli
          docker push sashas777/magento-php:7.4-cli